[package]
name = "service-registry"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
path = "src/"

[dependencies]
multiversx-sc = { version = "0.47.0", default-features = false }

[dev-dependencies]
multiversx-sc-scenario = "0.47.0"