server {
    listen 80;
    server_name localhost projecte.tudominio.com;
    root /var/www/projecte/public;
    index index.php;

    # Bloquear acceso a archivos sensibles
    location ~ /\. {
        deny all;
    }

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/run/php/php8.4-fpm.sock; # change to 8.4 debian 13
        try_files $uri=404;
    }

    # HTTPS (descomentar tras certbot)
    # listen 443 ssl;
    # ssl_certificate /etc/letsencrypt/live/projecte.tudominio.com/fullchain.pem;
    # ssl_certificate_key /etc/letsencrypt/live/projecte.tudominio.com/privkey.pem;
}